version: '2'

services:
  # nginx proxy
  nginx:
    build: ./nginx
    image: <%= appName %>/nginx
    networks:
      - default
    ports:
      - 443:443
    depends_on:
      - <%= appName %>

  # front end
  <%= appName %>:
    build: ./
    command: "/usr/local/bin/start-dev-container.sh"
    user: app
    env_file:
      - ./docker/npm-github-creds.dev
    tty: true
    expose:
      - 9000
    volumes:
      - .:/app
