version: '2'

services:
  # nginx proxy
  nginx:
    build: ./nginx
    image: <%= appName %>/nginx
    networks:
      - default
    ports:
      - 443:443
    depends_on:
      - <%= appName %>

  # front end
  <%= appName %>:
    build: ./
    command: "/usr/local/bin/start-dev-container.sh"
    user: app
    environment:
      NPM_REGISTRY: ${NPM_REGISTRY}
      NPM_USERNAME: ${NPM_USERNAME}
      NPM_PASSWORD: ${NPM_PASSWORD}
      NPM_EMAIL: ${NPM_EMAIL}
      JSPM_GITHUB_AUTH_TOKEN: ${JSPM_GITHUB_AUTH_TOKEN}
    tty: true
    expose:
      - 9000
    volumes:
      - .:/app
